title: Dave Mullen Jnr
author: Dave Mullen Jnr
email: dave@davemullenjnr.co.uk
description: Dave Mullen Jnr — Graphic designer and front-end web developer living in Sheffield, UK.
url: "https://davemullenjnr.co.uk"
social_username: davemullenjnr

# Collections
collections:
  projects:
    output: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Cloudinary
cloudinary:
  cloud_name: geometryclub
  only_prod: true
  verbose: true
  origin_url: /
  presets:
    default:
      min_width: 540
      max_width: 1620
      fallback_max_width: 1080
      steps: 3
      sizes: "(max-width: 540px) 540px, (max-width: 1080px) 1080px, 1620px"

github: [metadata]

theme_color: white

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
